### PR TITLE
Profile update

### PR DESCRIPTION
**Pull request by pranita-s**
I have added my profile picture in the _img_ folder and added a marked down document of my brief description in _people_ folder. Please let me know if anything is missing.

### CODE REVIEW

**Comment by ethanwhite** [comment]
Thanks @pranita-s! There are a couple of small changes to make:

1. Crop your picture to 1056 x 916 (or equivalent relative dimensions). This helps all of the images line up well.
2. Change the date to "2016-04-21". The theme sorts everything by date and this will put you in the right spot.
3. To distinguish from graduate students getting their degrees in the group let's use "Student Software Developer" in the `summary` field.

**Comment by pranita-s** [comment]
@ethanwhite Sure ! I will update accordingly

**Comment by pranita-s** [comment]
@ethanwhite I have corrected the fields and dimensions. Please review it.

**Comment by ethanwhite** [comment]
Thanks @pranita-s!

**Pull request merged**
